name: frontend:build_and_test

on:
  push:
    paths:
      - "frontend/**"
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - run: yarn install
      - run: yarn test

  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'

    steps:
      - uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Build container image"
        run: "gcloud builds submit --tag gcr.io/platinum-factor-345219/url-shortener-frontend"

      - name: "Deploy to Cloud Run"
        run: "gcloud run deploy --image gcr.io/platinum-factor-345219/url-shortener-frontend --platform managed --region=europe-west3"