name: functions:build_and_test

on:
  push:
    paths:
      - "functions/**"
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v2
        
      # some tests need access to Google Cloud Resources, e.g. Firestore
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go
          key: ${{ runner.os }}-build-${{ hashFiles('go.mod') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build code
        working-directory: ./functions
        run: |
          ROOT_DIR=$(pwd) \
          find . -name go.mod -execdir sh -c 'go build -v ./... || touch $ROOT_DIR/build_failed.txt' \; ; \
          test ! -f build_failed.txt

      - name: Test code
        working-directory: ./functions
        run: |
          ROOT_DIR=$(pwd) \
          find . -name go.mod -execdir sh -c 'go test -v ./... || touch $ROOT_DIR/tests_failed.txt' \; ; \
          test ! -f tests_failed.txt
