name: functions:deploy

on:
  push:
    paths:
      - "functions/**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      # every sub-directory of the 'functions' directory stands for a single Cloud Function.
      # this step iterates over every available directory and deploys it. The name of the Cloud Function
      # will be the same as its folder name.
      - name: "Deploy Cloud Function"
        working-directory: ./functions
        run: |
          for d in */; do cd $d; gcloud functions deploy ${d%?} --entry-point "Handle" --runtime go116 --trigger-http; done
