name: functions:build_and_test

on:
  push:
    paths:
      - "functions/**"
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Build code
        working-directory: ./functions
        run: find . -name go.mod -execdir sh -c 'go build -v ./...' \; ;

      - name: Test code
        working-directory: ./functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }} \
          find . -name go.mod -execdir sh -c 'go test -v ./...' \; ; \

