name: services:build_and_test

on:
  push:
    paths:
      - "services/**"
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        working-directory: ./services
        run: go build -v ./...

      - name: Test
        working-directory: ./services
        run: go test -v ./...
