name: services:deploy

on:
  push:
    paths:
      - "services/**"
    branches: [staging]

jobs:
  deploy:
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Deploy to Cloud"
        working-directory: ./services
        run: |
          for d in */; do \
              cd $d \
              sh ./deploy-function.sh \
          done
